---
---
:skip-front-matter:

= Problem Set 6: Sentimental

== tl;dr

. Watch Week 6's and Week 8's lecture.
. Port some programs from C to Python.
. Analyze some sentiments.

== Getting Started

If you have not set up your ide50 yet (i.e. you did not take programmeren ik earlier this year) please follow  link:/recourses/ide50[these instructions to set up IDE50]. Otherwise, head on over to https://cs50.io and enter the following commands in the terminal.

[source]
----
update50
mkdir ~/workspace/pset6/
cd ~/workspace/pset6/
----

== Problem: Sentiments

All code that you write should be consistent with https://www.python.org/dev/peps/pep-0008/[Style Guide for Python Code], otherwise known as PEP 8.

* Implement link:/problems/sentiments[Sentiments] in `pset6/sentiments/`.

== Hints

* Be sure to use Python 3, not Python 2.
* If a program is in a file called, say, `foo.py`, you can run that program with `python foo.py`.
* It is *not reasonable* to look at others' implementations of Sentiments.
* Insofar as a goal of this problem set is to teach you how to teach yourself a new language, keep in mind that these acts are not only *reasonable*, per the syllabus, but encouraged toward that end:
** Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite the lines' origins.
** Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.
* You're welcome to use the CS50 Library for Python, which includes `get_float`, `get_int`, and `get_string`. Just remember to include
+
[source]
import cs50
+
atop your code. Or you can use https://docs.python.org/3/library/functions.html#input[`input`] and validate users' input yourself.
* You might find https://docs.python.org/3/library/functions.html#chr[`chr`] and/or https://docs.python.org/3/library/functions.html#ord[`ord`] of help.
* You might find these references of interest:
** https://docs.python.org/3/reference/index.html[The Python Language Reference]
** https://docs.python.org/3/library/[The Python Standard Library]
** https://docs.python.org/3/tutorial/index.html[The Python Tutorial]

== Walkthrough

=== Problems 1 – 3

++++
<div class="sectionbody">
<div class="videoblock">
<div class="content">
<iframe src="https://video.cs50.net/2016/fall/psets/6/pset6/c-python" frameborder="0" allowfullscreen></iframe>
</div>
</div>
</div>
++++

=== Problem 4

See link:/problems/sentiments[Sentiments] for the walkthrough

== FAQs

=== AttributeError: 'module' object has no attribute `get_`

If seeing this error (for `cs50.get_char`, `cs50.get_float`, `cs50.get_int`, or `cs50.get_string`), try executing the below (which fixes a bug in an earlier version of the CS50 Library for Python):

[source]
----
sudo chmod -R a+rX /usr/lib/python2.7/dist-packages/cs50
sudo chmod -R a+rX /usr/lib/python3/dist-packages/cs50
----

=== ImportError: No module named 'sqlalchemy'

If seeing this error, execute

[source]
----
pip install --user sqlalchemy
----

to resolve!

== How to Submit

. Make sure you are signed in to this website!
. In the form below, add the files that you downloaded.
. Press "Submit for grading". Presto!

This was Problem Set 6.
